import { Prize } from "./prize";

export const participation1Prizes: Prize[] = [
  {
    name: "AI Ninja Zoom",
    description: "Zooming faster than your last relationship!",
    image: "Participation 1/AI Ninja Zoom.jpg",
    rarity: "common",
    available: true,
  },
  {
    name: "Banana Bros",
    description: "Peeling away your sanity, one slip at a time.",
    image: "Participation 1/Banana Bros.jpg",
    rarity: "common",
    available: true,
  },
  {
    name: "Besties",
    description: "Closer than your last awkward Tinder date.",
    image: "Participation 1/Besties.jpg",
    rarity: "common",
    available: true,
  },
  {
    name: "Boom Boom Pow",
    description: "Exploding with more drama than a reality TV show.",
    image: "Participation 1/Boom Boom Pow.jpg",
    rarity: "common",
    available: true,
  },
  {
    name: "DND Minis",
    description: "Smaller than your patience for bad dice rolls.",
    image: "Participation 1/DND Minis.jpg",
    rarity: "common",
    available: true,
  },
  {
    name: "Dirt Bikes Bro",
    description: "Kicking up more dirt than your last breakup.",
    image: "Participation 1/Dirt Bikes Bro.jpg",
    rarity: "common",
    available: true,
  },
  {
    name: "Lady Ninja",
    description: "Sneakier than your browser history.",
    image: "Participation 1/Lady Ninja.jpg",
    rarity: "common",
    available: true,
  },
  {
    name: "Mando Squad - 2",
    description: "More squad goals than your group chat.",
    image: "Participation 1/Mando Squad - 2.jpg",
    rarity: "common",
    available: true,
  },
  {
    name: "Mando Squard - 1",
    description: "Misspelled but still cooler than you.",
    image: "Participation 1/Mando Squard - 1.jpg",
    rarity: "common",
    available: true,
  },
  {
    name: "Metal Lizard",
    description: "Colder than your ex's heart.",
    image: "Participation 1/Metal Lizard.jpg",
    rarity: "common",
    available: true,
  },
  {
    name: "Old Lizard",
    description: "Older than your last excuse for being late.",
    image: "Participation 1/Old Lizard.jpg",
    rarity: "common",
    available: true,
  },
  {
    name: "Pokemon Snack - 1",
    description: "Tastier than your midnight regrets.",
    image: "Participation 1/Pokemon Snack - 1.jpg",
    rarity: "common",
    available: true,
  },
  {
    name: "Pokemon Snack - 2",
    description: "More addictive than your favorite app.",
    image: "Participation 1/Pokemon Snack - 2.jpg",
    rarity: "common",
    available: true,
  },
  {
    name: "Punchie Puncher",
    description: "Hits harder than your Monday morning.",
    image: "Participation 1/Punchie Puncher.jpg",
    rarity: "common",
    available: true,
  },
  {
    name: "Slice and Dice",
    description: "Sharper than your wit on a good day.",
    image: "Participation 1/Slice and Dice.jpg",
    rarity: "common",
    available: true,
  },
  {
    name: "Special Toucher",
    description: "More awkward than a family reunion.",
    image: "Participation 1/Special Toucher.jpg",
    rarity: "common",
    available: true,
  },
  {
    name: "The New Empire",
    description: "Ruling over your procrastination kingdom.",
    image: "Participation 1/The New Empire.jpg",
    rarity: "common",
    available: true,
  },
  {
    name: "Tony Bots",
    description: "More robotic than your morning routine.",
    image: "Participation 1/Tony Bots.jpg",
    rarity: "common",
    available: true,
  },
  {
    name: "Two Girls One Pokemon",
    description: "More controversial than your last tweet.",
    image: "Participation 1/Two Girls One Pokemon.jpg",
    rarity: "common",
    available: true,
  },
];
