import { Prize } from "./prize";

export const season4Prizes: Prize[] = [
  {
    name: "Belly Boy Box",
    description: "He probably already ate the cards inside...",
    image: "Season 4 - SlowBro/Belly Boy Box.jpg",
    rarity: "rare",
    available: true,
  },
  {
    name: "Can We Smoke This",
    description: "It's Green... It's Green... It's Green...",
    image: "Season 4 - SlowBro/Can We Smoke This.jpg",
    rarity: "uncommon",
    available: true,
  },
  {
    name: "Double Origin - 1",
    description: "One of Each!",
    image: "Season 4 - SlowBro/Double Origin - 1.jpg",
    rarity: "rare",
    available: true,
  },
  {
    name: "Fire Crocodile",
    description: "Bros mouth is a hibachi",
    image: "Season 4 - SlowBro/Fire Crocodile.jpg",
    rarity: "rare",
    available: true,
  },
  {
    name: "Is That You Dad",
    description: "How come dad looks like a Snorlax?",
    image: "Season 4 - SlowBro/Is That You Dad.jpg",
    rarity: "uncommon",
    available: true,
  },
  {
    name: "Metal Much",
    description: "Which one is harder?",
    image: "Season 4 - SlowBro/Metal Much.jpg",
    rarity: "rare",
    available: true,
  },
  {
    name: "OMG Origin",
    description: "Twinsies",
    image: "Season 4 - SlowBro/OMG Origin.jpg",
    rarity: "legendary",
    available: true,
  },
  {
    name: "Pika Pika",
    description: "OMG I Hope A Furry Is In There!",
    image: "Season 4 - SlowBro/Pika Pika.jpg",
    rarity: "uncommon",
    available: true,
  },
  {
    name: "Purple Snake Box",
    description: "Was this the one you wanted?",
    image: "Season 4 - SlowBro/Purple Snake Box.jpg",
    rarity: "legendary",
    available: true,
  },
  {
    name: "Red Lizard With a Mohawk",
    description: "I can't even describe these things",
    image: "Season 4 - SlowBro/Red Lizard With a Mohawk.jpg",
    rarity: "rare",
    available: true,
  },
  {
    name: "Red Turkey Box",
    description: "I am pretty sure this thing is part chicken",
    image: "Season 4 - SlowBro/Red Turkey Box.jpg",
    rarity: "legendary",
    available: true,
  },
  {
    name: "Saw Face",
    description: "He gives the warmest hugs",
    image: "Season 4 - SlowBro/Saw Face.jpg",
    rarity: "unique",
    available: true,
  },
  {
    name: "Scissor Box",
    description: "Just need one more box to scissor!",
    image: "Season 4 - SlowBro/Scissor Box.jpg",
    rarity: "uncommon",
    available: true,
  },
  {
    name: "Sleepy Bird",
    description: "Bro straight up fell asleep - skibidi",
    image: "Season 4 - SlowBro/Sleepy Bird.jpg",
    rarity: "rare",
    available: true,
  },
  {
    name: "Snack Pack - 1",
    description: "Just a bump till next time",
    image: "Season 4 - SlowBro/Snack Pack - 1.jpg",
    rarity: "uncommon",
    available: true,
  },
  {
    name: "Snack Pack - 2",
    description: "Puff puff pass",
    image: "Season 4 - SlowBro/Snack Pack - 2.jpg",
    rarity: "uncommon",
    available: true,
  },
  {
    name: "Warm Hugs",
    description: "With his teeth",
    image: "Season 4 - SlowBro/Warm Hugs.jpg",
    rarity: "rare",
    available: true,
  },
  //
  {
    name: "Ghost Pikachu",
    description: "Is it really Inosuke under there?",
    image: "Season 4 - SlowBro/Ghost Pikachu.jpg",
    rarity: "unique",
    available: false,
  },
  {
    name: "Kangaroo Cream",
    description: "Half kangaroo, half cream",
    image: "Season 4 - SlowBro/Kangaroo Cream.jpg",
    rarity: "uncommon",
    available: false,
  },
];
