import { Prize } from "./prize";

export const season2Prizes: Prize[] = [
  {
    name: "Dinner Time",
    description: "Who let Rexie out?",
    image: "Season 2/Dinner Time.jpg",
    rarity: "legendary",
    available: true,
  },
  {
    name: "Dont Tazz Me Bro",
    description: "It can smell your fear?",
    image: "Season 2/Dont Tazz Me Bro.jpg",
    rarity: "legendary",
    available: true,
  },
  {
    name: "Fried Eggz",
    description: "Get 'em Sanic!",
    image: "Season 2/Fried Eggz.jpg",
    rarity: "rare",
    available: true,
  },
  {
    name: "Get In Line",
    description: "Line up for cigarette burns!",
    image: "Season 2/Get In Line.jpg",
    rarity: "rare",
    available: true,
  },
  {
    name: "Nintendo vs Sega",
    description: "A tale as old as time",
    image: "Season 2/Nintendo vs Sega.jpg",
    rarity: "rare",
    available: true,
  },
  {
    name: "Pretty Bird",
    description: "You think she has a girlfriend?",
    image: "Season 2/Pretty Bird.jpg",
    rarity: "legendary",
    available: true,
  },

  {
    name: "Street Pharmacist",
    description: "First hit is free",
    image: "Season 2/Street Pharmacist.jpg",
    rarity: "uncommon",
    available: true,
  },
  {
    name: "Save the Princess",
    description: "She puts out...",
    image: "Season 2/Save the Princess.jpg",
    rarity: "uncommon",
    available: true,
  },
  {
    name: "Storm the Church",
    description: "Why are there children here?",
    image: "Season 2/Storm the Church.jpg",
    rarity: "uncommon",
    available: true,
  },
  {
    name: "The Armory",
    description: "Time to suite up!",
    image: "Season 2/The Armory.jpg",
    rarity: "legendary",
    available: true,
  },
  {
    name: "The Creator",
    description: "Ten Legos in one?",
    image: "Season 2/The Creator.jpg",
    rarity: "uncommon",
    available: true,
  },
  {
    name: "The Elites",
    description: "Not your average clones",
    image: "Season 2/The Elites.jpg",
    rarity: "uncommon",
    available: true,
  },
  {
    name: "The Hero We Need",
    description: "Molded by the darkness, his parents are dead",
    image: "Season 2/The Hero We Need.jpg",
    rarity: "rare",
    available: true,
  },
  {
    name: "Thigh Master",
    description: "This looks like exercise equipment",
    image: "Season 2/Thigh Master.jpg",
    rarity: "legendary",
    available: true,
  },

  {
    name: "What Does the Fox Say",
    description: "Hacki hacki hacki ho",
    image: "Season 2/What Does the Fox Say.jpg",
    rarity: "legendary",
    available: true,
  },
  {
    name: "Yoda Save Me",
    description: "Don't use the force on my butthole",
    image: "Season 2/Yoda Save Me.jpg",
    rarity: "uncommon",
    available: true,
  },
  //
  {
    name: "Final Boss",
    description: "You Win! Skibidi Sigma",
    image: "Season 2/Final Boss.jpg",
    rarity: "unique",
    available: false,
  },
  {
    name: "He Wants To Touch It",
    description: "At least it's not a furry",
    image: "Season 2/He Wants To Touch It.jpg",
    rarity: "legendary",
    available: false,
  },
  {
    name: "Wanna Jump It",
    description: "WWWwwwweeeeeeEEEEEeeeeee...",
    image: "Season 2/Wanna Jump It.jpg",
    rarity: "common",
    available: false,
  },
  {
    name: "Save the Child",
    description: "Don't play with your nuggies",
    image: "Season 2/Save the Child.jpg",
    rarity: "rare",
    available: false,
  },
  {
    name: "Welcome To Potter Park",
    description: "Half man, half bird, half car",
    image: "Season 2/Welcome To Potter Park.jpg",
    rarity: "rare",
    available: false,
  },
  {
    name: "Butthole Shield",
    description: "Don't Let It In!",
    image: "Season 2/Butthole Shield.jpg",
    rarity: "rare",
    available: false,
  },
  {
    name: "Check Please",
    description: "When you need to get out like now",
    image: "Season 2/Check Please.jpg",
    rarity: "legendary",
    available: false,
  },
  {
    name: "Flower Power",
    description: "All the mushrooms he can eat...",
    image: "Season 2/Flower Power.jpg",
    rarity: "uncommon",
    available: false,
  },
  {
    name: "Hulk Smash",
    description: "Hulk Want Mush Mush",
    image: "Season 2/Hulk Smash.jpg",
    rarity: "legendary",
    available: false,
  },
  {
    name: "Step Step Step",
    description: "Death by Dubstep",
    image: "Season 2/Step Step Step.jpg",
    rarity: "legendary",
    available: false,
  },
];
